### ISSUE TITLE
Merges to master do not auto-update network.filecoin.io

### ISSUE THREAD

**Issue by eshon** [filecoin-project/network-info#24]
`ntwk-nerpa-8.28.0` info was merged to master at 21:35 UTC, as of 22:00 UTC the website at https://network.filecoin.io still hasn't auto-updated.

If you check it now and `ntwk-nerpa-8.28.0` is not under Nerpa this is still an issue.

**Comment by orvn** [comment]
@eshon, you're right. The merge passed tests and generated [this preview URL](https://bafybeigeqrmdf5dda5uobaeptmfyeaekr2tzonrk7hnr5mmjqgxbwaknoe.on.fleek.co/) from Fleek.

However, those changes aren't visible on the production url: https://network.filecoin.io/#nerpa _(as of 23:20 UTC)_

**Comment by andyschwab** [comment]
Should be corrected. Looked like the original deploy was partially broken.
