### ISSUE TITLE
Render "Consensus Miner Min Power" as GiB or TiB, etc

### ISSUE THREAD

**Issue by pooja** [filecoin-project/network-info#4]
Currently the site renders Consensus Miner Min Power as the raw byte number. It would be more human-readable if we could label it with GiB or TiB, etc.

Can we please include this in a future upgrade? Thanks!

**Comment by orvn** [comment]
Yes absolutely, will make that change @pooja

**Comment by pooja** [comment]
Thanks!

**Comment by orvn** [comment]
Units have been added to convert bytes into the IEC notation (MiB, KiB, GiB, etc.)
