### ISSUE TITLE
Is there an external node？

### ISSUE THREAD

**Issue by Wangmmx** [filecoin-project/network-info#44]
Is there an external node that can be directly connected with `curl`？
Both Lotus and Space Race are fine
Thanks a lot

**Comment by hsanjuan** [comment]
https://docs.filecoin.io/build/hosted-lotus/

**Comment by Wangmmx** [comment]
> https://docs.filecoin.io/build/hosted-lotus/

Thanks a lot!
When I connect to an external node `https://api.node.glif.io` and use certain interfaces, such as `Filecoin.WalletBalance`, an error {"message":"Missing Authentication Token"} is reported. 
How do I get the Token? Or do these methods do not support external nodes?
