### ISSUE TITLE
Nerpa info not updating with PR merge to master

### ISSUE THREAD

**Issue by eshon** [filecoin-project/network-info#58]
I updated Nerpa over 15 minutes ago with the PR https://github.com/filecoin-project/network-info/pull/57  but still don’t see an update at https://network.filecoin.io/#nerpa

**Comment by orvn** [comment]
@eshon, yeah everything looked successful [in the log](https://github.com/filecoin-project/network-info/runs/1316606596). I triggered a rebuild and it built correctly. 

It could have indeed had something to do with the Github service issue from today as you mentioned.

In the future, if this happens, you can force a rebuild by merging any commit in. I edited the `readme.md` to trigger a build. It can also be done from within Fleek (I don't have access to it directly).
